/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseDate: typeof import('./src/components/BaseDate.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    ForumList: typeof import('./src/components/ForumList.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PostEditor: typeof import('./src/components/PostEditor.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    ThreadEditor: typeof import('./src/components/ThreadEditor.vue')['default']
    ThreadList: typeof import('./src/components/ThreadList.vue')['default']
    UserProfileCardDetails: typeof import('./src/components/UserProfileCardDetails.vue')['default']
    UserProfileCardEditor: typeof import('./src/components/UserProfileCardEditor.vue')['default']
  }
}
